apiVersion: apps/v1
kind: Deployment
metadata: 
  name: traefik
  labels: 
    app: traefik
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
                         # during the rolling update
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
        aadpodidbinding: traefikssl-selector
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60    
      containers:
      - image: traefik:1.7.7-alpine 
        name: traefik
        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "30Mi"
        readinessProbe:
          tcpSocket:
            port: 80 
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80 
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - name: certs 
          mountPath: /certs
        - name: config 
          mountPath: /config
        ports:
        - name: http
          containerPort: 80 
          protocol: TCP
        - name: https
          containerPort: 443 
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: traefik
      - name: certs
        flexVolume:
          driver: "azure/kv"
          options: 
            keyvaultname: "<KV-Name>"
            keyvaultobjectname: tls-pem;tls-key 
            keyvaultobjectaliases: tls-pem.pem;tls-key.key
            keyvaultobjecttype: secret;secret
            tenantid: "#######-##########-#########"
            usepodidentity: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  labels:
    app: traefik
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: traefik
  ports:
  - port: 443
    name: https
