apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds                  # [OPTIONAL] not required if using Pod Identity
      options:
        usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: ""               # the name of the KeyVault
        keyvaultobjectnames: test1;test2    # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret;secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: ""              # [REQUIRED FOR < v0.0.13] the resource group of the KeyVault	
        subscriptionid: ""             # [REQUIRED FOR < v0.0.13] the subscription ID of the KeyVault
        tenantid: ""                   # the tenant ID of the KeyVault
