#!/bin/sh

DIR=$(dirname "$(readlink -f "$0")")
JQ="/usr/bin/jq"
LOG="/var/log/kv-driver.log"
VER="0.0.3"

usage() {
	err "Invalid usage. Usage: "
	err "\t$0 init"
	err "\t$0 mount <mount dir> <json params>"
	err "\t$0 unmount <mount dir>"
	exit 1
}

err() {
	echo $* 1>&2
}

log() {
	echo $* >&1
}

mount() {
	MNTPATH="$1"

	CLIENTID="$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/clientid"] // empty' | base64 -d)"
	CLIENTSECRET="$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/clientsecret"] // empty' | tr -d '\n' | tr -d ' ' | base64 -d)"
	TENANT="$(echo "$2"|"$JQ" -r '.["kubernetes.io/secret/tenant"] // empty' | tr -d '\n' | tr -d ' ' | base64 -d)"
	
	FS_TYPE="$(echo "$2"|"$JQ" -r '.["kubernetes.io/fsType"] //empty')"
	READ_WRITE="$(echo "$2"|"$JQ" -r '.["kubernetes.io/readwrite"] //empty')"
	# Required
	REGION="$(echo "$2"|"$JQ" -r '.region //empty')"
	CLOUD_NAME="$(echo "$2"|"$JQ" -r '.cloudname //empty')"
	RESOURCE_GROUP="$(echo "$2"|"$JQ" -r '.resourcegroup //empty')"
	SUBSCRIPTION_ID="$(echo "$2"|"$JQ" -r '.subscriptionid //empty')"
	TENANT_ID="$(echo "$2"|"$JQ" -r '.tenantid //empty')"

	KEYVAULT_NAME="$(echo "$2"|"$JQ" -r '.keyvaultname //empty')"
	KEYVAULT_OBJECT_NAME="$(echo "$2"|"$JQ" -r '.keyvaultobjectname //empty')"
	KEYVAULT_OBJECT_TYPE="$(echo "$2"|"$JQ" -r '.keyvaultobjecttype //empty')"
	# Optional
	KEYVAULT_OBJECT_VERSION="$(echo "$2"|"$JQ" -r '.keyvaultobjectversion //empty')"
	USE_INTEGRATED_ID="$(echo "$2"|"$JQ" -r '.useintegratedid //empty')"
	ALIAS="$(echo "$2"|"$JQ" -r '.alias //empty')"
	
	echo "`date` CLIENTID: ${CLIENTID}" >>$LOG

	read_only_param=""
	if [ $READ_WRITE = "ro" ]; then
		read_only_param="--read-only"
	fi

	echo "`date` EXEC: mkdir -p ${MNTPATH}" >> $LOG
	mkdir -p ${MNTPATH} >>$LOG 2>&1

	echo "`date` EXEC: /etc/kubernetes/volumeplugins/azure~kv/azurekeyvault-flexvolume -logtostderr=1 -vaultName=${KEYVAULT_NAME} -secretName=${KEYVAULT_OBJECT_NAME} -resourceGroup=${RESOURCE_GROUP} -dir=${MNTPATH}/${KEYVAULT_OBJECT_NAME}.txt -subscriptionId=${SUBSCRIPTION_ID} -cloudName="" -tenantId=${TENANT_ID} -aADClientSecret=${CLIENTSECRET} -aADClientID=${CLIENTID}" >> $LOG
	/etc/kubernetes/volumeplugins/azure~kv/azurekeyvault-flexvolume -logtostderr=1 -vaultName=${KEYVAULT_NAME} -secretName=${KEYVAULT_OBJECT_NAME} -resourceGroup=${RESOURCE_GROUP} -dir=${MNTPATH} -subscriptionId=${SUBSCRIPTION_ID} -cloudName="" -tenantId=${TENANT_ID} -aADClientSecret=${CLIENTSECRET} -aADClientID=${CLIENTID} >>$LOG 2>&1
	
	echo "`date` EXEC: ls ${MNTPATH}" >> $LOG

	errorLog=`tail -n 1 "${LOG}"`
	log "{\"status\": \"Success\",\"message\":\"log:${errorLog}\" }"
	exit 0
}

unmount() {
	MNTPATH="$1"

	log '{"status": "Success"}'
	exit 0
}

## ---------------
## main
## ---------------

op=$1

if [ "$op" = "init" ]; then
	log '{"status": "Success", "capabilities": {"attach": false}}'
	exit 0
fi

if [ $# -lt 2 ]; then
	usage
fi

shift

case "$op" in
	mount)
		mount $*
		;;
	unmount)
		unmount $*
		;;
	*)
	usage
esac

exit 1
